### ISSUE TITLE
Release 0.11.0

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#1236]
# Release Notes

- Web UI: [`v2.5.1`](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.5.1)
- IPFS: [`go-ipfs v0.4.22`](https://github.com/ipfs/go-ipfs/releases/tag/v0.4.22)

### 🚨 Breaking Changes

- [ ] Remove code to disable old auto launch at startup.

### ✨  Features

- [ ] `js-ipfs` implementation support (#601)
- [ ] Move configuration to one place (#1082)
- [ ] Improve UX of 'Download Hash' (#1135)

Postponed from #951:

- [ ] New Tray Icon (#956)
- [ ] Co-host websites (#1034)

### 🛠 Fixes and Maintenance

_If any..._

# Before Release

- [ ] Make sure i18n is updated (`tx pull -a`)
- [ ] Make sure we're using the latest released version of Web UI
- [ ] Make sure we're using the latest released version of `go-ipfs`
- [ ] Update Release Notes accordingly

# Release

- [ ] Release Candidate
	- [ ] 💻 Bump version on `package.json`
	- [ ] 💻 `git tag $version`
	- [ ] 💻 `git push && git push --tags`
	- [ ] ⏰ Wait...
	- [ ] 🔗 Link release notes to this issue
- [ ] Final
	- [ ] 📝 Create draft and copy the release notes above
	- [ ] 💻 Bump version on `package.json`
	- [ ] 💻 `git tag $version`
	- [ ] 💻 `git push && git push --tags`
	- [ ] ⏰ Wait...
	- [ ] 📃 Copy the release notes above to the GitHub release
	- [ ] 🚢 Ship!
	- [ ] 📑 Update README.md versions
	- [ ] 📦 Update Homebrew
	- [ ] 📦 Update Chocolatey

# Postponed

_If any..._

**Comment by andrew** [comment]
This issue seems a bit outdated given that [0.10.4](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.10.4) has newer versions of webui and go-ipfs than this issue.

Also I believe "New Tray Icon" has already been shipped.
