### ISSUE TITLE
Fix menu → Take screenshot

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#1663]
Right now a screenshot is taken and added to IPFS and a link is copied to clipboard, but not added to _Files_.

## TODO

- [x] seems that copied link is broken right now (and uses share.ipfs.io atm)
  - I was testing and copied link was `https://share.ipfs.io/#undefined`, but that could be due to Electron 10 tests - needs analysis
  - copied link should be `https://ipfs.io/ipfs/<cid>?filename=<name-from-mfs>` 
- [x] make sure `ipfs add` is executed with `--pin=false`
- [x] add imported file to MFS
  - avoid messy root by adding it to `screenshots/YYYY-MM-DD_HH-MM-SS.png` ?

**Comment by lidel** [comment]
Fixed in https://github.com/ipfs-shipyard/ipfs-desktop/pull/1689, released in [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2)
