### ISSUE TITLE
Release 0.7 💌✨ signed, sealed, delivered, I'm yours.

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-desktop#788]
> A fixes and certs release. A robust release that installs without warnings, auto-updates, and runs for days without error.

**Disclaimer:** the content of this main/first comment will be gradually updated with the current state and decisions related to this proccess.

## Checklist

- [x] Binary signing for macOS https://github.com/ipfs-shipyard/ipfs-desktop/issues/66
- [x] Binary signing for Windows https://github.com/ipfs-shipyard/ipfs-desktop/issues/705
- [x] Add tests for start up and shut down
- [x] Dont' error if shutdown called more than once https://github.com/ipfs-shipyard/ipfs-desktop/issues/776
- [x] Verify auto-update process https://github.com/ipfs-shipyard/ipfs-desktop/issues/783
- [x] Add self-hosted analytics https://github.com/ipfs-shipyard/ipfs-webui/pull/985
- [x] "Add to IPFS" OS context menu https://github.com/ipfs-shipyard/ipfs-desktop/issues/678
	- Only implemented on Windows. For more information see #678.
- [x] Upgrade to go-ipfs 0.4.19 https://github.com/ipfs-shipyard/ipfs-desktop/issues/864
- [ ] Add new section linking to IPFS Desktop in ipfs.io (https://github.com/ipfs/website/pull/297)

**Comment by hacdias** [comment]
As @lidel said on IRC, I think we should tell people that Linux support is experimental and focus more on Windows and macOS for now.

We can continue providing the binaries, but since a lot of stuff can vary on linux, it is harder to support every different Desktop Environment. Also, usually Linux users are more technical and prone to have their own setup. But for Windows and macOS, generally everything is more visual (and that's what IPFS Desktop is) so I think we should focus more on making this work better now on Windows and macOS.

**Comment by hacdias** [comment]
@olizilla I think we should release 0.7 next week after merging #826 so we can test the new features and ask users for feedback.

**Comment by hacdias** [comment]
Just an update on this matter: we finally have signed binaries for both Windows and macOS. We also have a context menu option working well on Windows and `ipfs://`, `ipns://` and `dweb://` handlers working well on Windows and macOS (the latter only if IPFS Desktop is running).

I believe #776 was fixed with a commit I did during the past days, but let's not close it right now, just to make sure it's fixed.

Tests were also added for many start up scenes. The shutting down isn't explicitly tested but the app shuts down every time a startup test runs so I believe it counts.

**Comment by hacdias** [comment]
Another update about the missing points:

> Add self-hosted analytics https://github.com/ipfs/ipfs-gui/issues/72

@olizilla I think we should postpone this one due to the recent discussion.

> "Add to IPFS" OS context menu https://github.com/ipfs-shipyard/ipfs-desktop/issues/678

Done on Windows. I can't try right now on macOS. Soon I can try to find out if it's feasible.

> Add new section linking to IPFS Desktop in ipfs.io (https://github.com/ipfs/website/pull/282)

Can be easily done.

---

There seems to be an issue with macOS update not quitting the app.

**Comment by olizilla** [comment]
@hacdias on "verify auto-update process" did you see https://www.electron.build/auto-update#debugging and https://github.com/electron-userland/electron-builder/issues/3053#issuecomment-401001573

**Comment by olizilla** [comment]
@hacdias 0.7 is go!

**Comment by hacdias** [comment]
I'm closing this since it was already released!! 😄
