### ISSUE TITLE
Release 0.9 📦 npm-on-ipfs & wild files 🦌

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-desktop#951]
# Release Notes

- Web UI: [`v2.5.1`](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.5.1)
- IPFS: [`go-ipfs v0.4.22`](https://github.com/ipfs/go-ipfs/releases/tag/v0.4.22)

The 0.9.0 version now allows you to navigate, not only your own files and pins, but the whole `/ipfs` and `/ipns` universe. Just type a path and you're good to go. We've also improved many existing features and squashed a lot of bugs.

### 🚨 Breaking Changes

- The accelerator for 'Take Screenshot' on macOS is now `Command+Control+S`
- The accelerator for 'Download Hash' on macOS is now `Command+Control+H`

### ✨  Features

- [x] Add `npm-on-ipfs` support (#911)
- [x] Add `Cmd+Q` accelerator to quit the app on macOS (#976)
- [x] Add `Cmd+R` accelerator to restart the node on macOS (#1025)
- [x] Add 'Take Screenshot' and 'Download Hash' to menubar (#977)
- [x] 'Download Hash' feature now supports any IP(F)(N)S paths (#980)
- [x] Protocol handlers (`ipns://`, `ipfs://`, `dweb:`) now use the local gateway when available (#994)
- [x] Navigate files in the wild (#922, https://github.com/ipfs-shipyard/ipfs-webui/pull/1027)
- [x] Allow to move repository location (#988)
- [x] Upgrade to Electron 6.0 (#1012)
- [x] `go-ipfs v0.4.22`

### 🐛 Fixes and Maintenance

- [x] Fix `ipfs-on-path` install script path on Windows (#964)
- [x] Fix permission errors on macOS/Linux when installing `ipfs-on-path` (#959)
- [x] 'Download Hash' feature now can download nested directories successfully (#980)
- [x] Use a different shortcut to download hashes on macOS (#981)
- [x] Handle the case where default ports are busy (#912)
- [x] Make sure we stop IPFS before quitting (#1022)
- [x] Get `go-ipfs` version from `go-ipfs.version` or `go-ipfs-dep` (#1037)
- [x] Fix notify import (#1036)
- [x] Increase draggable area on window to be easily moved (#1066)
- [x] Introduce unit tests (#1038, #1070)
- [x] Have a reliable CI process (#973, #1055)

# Before Release

- [x] Make sure i18n is updated (`tx pull -a`)
- [x] Make sure we're using the latest released version of Web UI
- [x] Make sure we're using the latest released version of `go-ipfs`
- [x] Update Release Notes accordingly

# Release

- [x] Release Candidate
	- [x] 💻 Bump version on `package.json`
	- [x] 💻 `git tag $version`
	- [x] 💻 `git push && git push --tags`
	- [x] ⏰ Wait...
	- [x] 🔗 Link release notes to this issue
- [x] Final
	- [x] 📝 Create draft and copy the release notes above
	- [x] 💻 Bump version on `package.json`
	- [x] 💻 `git tag $version`
	- [x] 💻 `git push && git push --tags`
	- [x] ⏰ Wait...
	- [x] 📃 Copy the release notes above to the GitHub release
	- [x] 🚢 Ship!
	- [x] 📑 Update README.md versions
	- [x] 📦 Update Homebrew
	- [x] 📦 Update Chocolatey

# Postponed

- [ ] New Tray Icon (#956)
- [ ] Co-host websites (#1034)
- [ ] Analytics Improved (#1063)

**Comment by enOehTsIsihT** [comment]
v0.9.0-beta.1 has black screen issue.

OS : win 7

**Comment by hacdias** [comment]
Just tested on a clean install of Windows 10 and could not reproduce. Is this the screen you're talking about?

<img width="1440" alt="Screenshot 2019-08-15 at 08 46 01" src="https://user-images.githubusercontent.com/5447088/63080509-2c5f6080-bf39-11e9-8714-d6fe5202efa5.png">

**Comment by enOehTsIsihT** [comment]
![black screen issue](https://user-images.githubusercontent.com/11388444/63093910-7415d480-bf99-11e9-8dc6-2655754de2d9.jpg)
If Microsoft .NET Framework is 4.5.2, the issue could be reproduced.

After updating Microsoft .NET Framework, ipfs-desktop work fine now.

**Comment by hacdias** [comment]
@enOehTsIsihT probably an issue regarding Electron or Electron Builder then (or just .NET Framework...). Will take a look.

**Comment by hacdias** [comment]
[v0.9.0](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.9.0) released! 🎊
